// reactjs/src/App.tsx
import { useEffect, useState } from 'react'
import reactLogo from './assets/react.svg'
import viteLogo from '/vite.svg'
import './App.css'

function App() {
  const [time, setTime] = useState(0);
  const [isRunning, setIsRunning] = useState(false);

  const [lapTime, setLapTime] = useState<number[]>([]);

  useEffect(() => {
    let interval: number | undefined;

    if(isRunning){
      interval = setInterval(() => setTime(time + 1), 1000);
    }

    return () => clearInterval(interval);
  }, [isRunning, time]);

  const minutes = Math.floor(time / 60);
  const seconds = Math.floor(time % 60);

  const startAndResume = function(){
    setIsRunning(true);
  };

  const stop = function(){
    setIsRunning(false);
  };

  const reset = function(){
    setIsRunning(false);
    setTime(0);
    setLapTime([]);
  };

  const lap = function(){
    setLapTime([...lapTime, time]);
  };

  return (
    <>
      <div>
        <a href="https://vitejs.dev" target="_blank">
          <img src={viteLogo} className="logo" alt="Vite logo" />
        </a>
        <a href="https://react.dev" target="_blank">
          <img src={reactLogo} className="logo react" alt="React logo" />
        </a>
      </div>
      <h1>Vite + React</h1>
      <div>
        {minutes}:{seconds}
      </div>
      <div className="card">
        <div style={{display: 'flex'}}>
          {isRunning === false ? (
            <button onClick={() => startAndResume()}>
              Start/Resume
            </button>
          ) : (
            <button onClick={() => stop()}>
              Stop
            </button>
          )}
          <button onClick={() => reset()}>
            Reset
          </button>
          <button onClick={() => lap()}>
            Lap
          </button>
        </div>
        <ul>
          {lapTime.map((value, index) => (
            <li key={index}>{Math.floor(value / 60)}:{Math.floor(value % 60)}</li>
          ))}
        </ul>
        <p>
          Edit <code>src/App.tsx</code> and save to test HMR
        </p>
      </div>
      <p className="read-the-docs">
        Click on the Vite and React logos to learn more
      </p>
    </>
  )
}

export default App

// svelte/src/App.svelte
<script lang="ts">
  import svelteLogo from './assets/svelte.svg'
  import viteLogo from '/vite.svg'
  import Counter from './lib/Counter.svelte'
  import Stopwatch from './lib/Stopwatch.svelte'
</script>

<main>
  <div>
    <a href="https://vitejs.dev" target="_blank" rel="noreferrer">
      <img src={viteLogo} class="logo" alt="Vite Logo" />
    </a>
    <a href="https://svelte.dev" target="_blank" rel="noreferrer">
      <img src={svelteLogo} class="logo svelte" alt="Svelte Logo" />
    </a>
  </div>
  <h1>Vite + Svelte</h1>

  <div class="card">
    <Counter />
  </div>

  <div class="card">
    <Stopwatch />
  </div>

  <p>
    Check out <a href="https://github.com/sveltejs/kit#readme" target="_blank" rel="noreferrer">SvelteKit</a>, the official Svelte app framework powered by Vite!
  </p>

  <p class="read-the-docs">
    Click on the Vite and Svelte logos to learn more
  </p>
</main>

<style>
  .logo {
    height: 6em;
    padding: 1.5em;
    will-change: filter;
    transition: filter 300ms;
  }
  .logo:hover {
    filter: drop-shadow(0 0 2em #646cffaa);
  }
  .logo.svelte:hover {
    filter: drop-shadow(0 0 2em #ff3e00aa);
  }
  .read-the-docs {
    color: #888;
  }
</style>
